# Main Web Server Configuration

server {
    listen 0000;
    server_name amman.com www.amman.com;

    error_page 404 /errors/404.html;
    error_page 500 /errors/500.html;

    location / {
        allow_methods GET POST;
        autoindex off;
    }

    location /images {
        allow_methods GET;
        autoindex on;
    }

    location /cgi-bin {
        allow_methods GET POST;
        cgi_ext .py;
        cgi_path /usr/bin/python3;
    }
}

# Secondary Test Server on the same port
server {
    listen 8080;
    server_name localhost;

    location /old-page {
        return 301 https://google.com;
    }
}