# السيرفر الرئيسي للموقع
server 



{
    listen 8080;








    host 0.0.0.0;
    server_name amman.com www.amman.com;
    client_max_body_size 20M;

    error_page 404 /errors/404.html;
    error_page 500  /errors/50x.html;

    location / {
        allow_methods GET POST;
        root /var/www/html;








        index index.html  ;
        autoindex off ;
    }

    location /images 
	{
        allow_methods GET; 
        root /var/www/data;
        autoindex on;
    }

    location /cgi-bin{
        allow_methods GET POST;
        root /var/www/cgi;
        cgi_ext .py;
        cgi_path /usr/bin/python3;
	}
}

server {
    listen 9090;
    host localhost;
    server_name test.com;
    client_max_body_size 500K;

    location /old-page {
        allow_methods GET;
        return 301 https://google.com;
    }
}