server {
    listen 127.0.0.1:8080;
    server_name localhost;
    client_max_body_size 10M;

    root www/cgi-bin;
    index hello.py;

    location / {
        root www/cgi-bin;
        methods GET POST;
        cgi_ext .py /usr/bin/python3;
        cgi_ext .sh /bin/bash;
        autoindex on;
    }
}
