server {
    listen 127.0.0.1:8080;
    server_name site1.local localhost;
    client_max_body_size 5M;

    root www/site;
    index index.html;

    location / {
        root www/site;
        index index.html;
        methods GET POST;
        autoindex on;
    }
}

server {
    listen 127.0.0.1:8081;
    server_name site2.local;
    client_max_body_size 1M;

    root www/uploads;
    index index.html;

    location / {
        root www/uploads;
        methods GET POST DELETE;
        upload_dir www/uploads;
        autoindex on;
    }
}

server {
    listen 127.0.0.1:8082;
    server_name site3.local;
    client_max_body_size 2M;

    root www/cgi-bin;

    location / {
        root www/cgi-bin;
        methods GET POST;
        cgi_ext .py /usr/bin/python3;
        cgi_ext .sh /bin/bash;
        autoindex on;
    }
}
