server {
    listen 127.0.0.1:8080;
    server_name myserver.com;
    root www/site;

    location / {
        methods GET;
    }
}

server {
    listen 127.0.0.1:8080;
    server_name myserver.com;
    root www/site;

    location / {
        methods GET;
    }
}
