server {
    listen 127.0.0.1:8080;
    server_name localhost;
    client_max_body_size 10M;

    error_page 403 /errors/403.html;
    error_page 404 /errors/404.html;
    error_page 405 /errors/405.html;
    error_page 413 /errors/413.html;
    error_page 500 /errors/500.html;
    error_page 504 /errors/504.html;

    root www/site;
    index index.html;

    location / {
        root www/site;
        index index.html;
        methods GET POST;
        upload_dir www/uploads;
        autoindex on;
    }

    location /auto_on {
        root www/eval/auto_on;
        methods GET;
        autoindex on;
    }

    location /has_index {
        root www/eval/has_index;
        index index.html;
        methods GET;
        autoindex off;
    }

    location /no_index {
        root www/eval/no_index;
        methods GET;
        autoindex off;
    }

    location /uploads {
        root www/uploads;
        methods GET POST DELETE;
        upload_dir www/uploads;
        autoindex on;
    }

    location /cgi-bin {
        root www/cgi-bin;
        methods GET POST;
        cgi_ext .py /usr/bin/python3;
        cgi_ext .sh /bin/bash;
        cgi_ext .pl /usr/bin/perl;
        cgi_ext .php /usr/bin/php-cgi;
    }

    location /restricted {
        root www/site;
        methods GET;
    }

    location /noupload {
        root www/site;
        methods GET POST;
    }

    location /redirect {
        return 301 /;
    }

    location /google {
        return 302 https://www.google.com;
    }
}
