server {
    listen 127.0.0.1:8093;
    server_name localhost;
    client_max_body_size 10M;

    root www/site;
    index index.html;

    location /only_get {
        root www/site;
        index index.html;
        methods GET;
    }

    location /get_post {
        root www/uploads;
        methods GET POST;
        upload_dir www/uploads;
    }
}
