server {
    listen 127.0.0.1:8084;
    server_name server1.com;
    root www/eval/server1;
    index index.html;

    location / {
        root www/eval/server1;
        index index.html;
        methods GET;
    }
}

server {
    listen 127.0.0.1:8085;
    server_name server2.com;
    root www/eval/server2;
    index index.html;

    location / {
        root www/eval/server2;
        index index.html;
        methods GET;
    }
}
