server {
    listen 127.0.0.1:8082;
    server_name localhost;
    client_max_body_size 10M;

    root www/uploads;

    location /upload {
        root www/uploads;
        methods GET POST DELETE;
        upload_dir www/uploads;
        autoindex on;
    }
}
