#include <arpa/inet.h>
#include <cstdlib>
#include <cstring>
#include <iostream>
#include <netdb.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <unistd.h>
#include <vector>
#include <bits/stdc++.h>
#include <fstream>
#include <iostream>
#include <map>
#include <stack>
