#!/usr/bin/env python3
import os
import sys
import cgi

# Get query params
query = os.environ.get("QUERY_STRING", "")
params = {}
if query:
    for part in query.split("&"):
        if "=" in part:
            k, v = part.split("=", 1)
            params[k] = v

name = params.get("name", "World")

# Read POST body if applicable
method = os.environ.get("REQUEST_METHOD", "GET")
body = ""
if method == "POST":
    content_length = int(os.environ.get("CONTENT_LENGTH", 0) or 0)
    if content_length > 0:
        body = sys.stdin.read(content_length)

print("Content-Type: text/html\r")
print("\r")
print("""<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>CGI Hello</title>
  <style>
    body {{ background:#0f1117; color:#e0e0e0; font-family:monospace; padding:40px; }}
    h1 {{ color:#7eb3ff; }}
    table {{ border-collapse:collapse; margin-top:20px; }}
    th,td {{ border:1px solid #2a2a4a; padding:6px 14px; text-align:left; }}
    th {{ background:#1a1a2e; color:#7eb3ff; }}
    .back {{ color:#7eb3ff; text-decoration:none; }}
  </style>
</head>
<body>
  <h1>Hello, {name}!</h1>
  <p>This response was generated by a Python CGI script.</p>
  <h2 style="color:#888; margin-top:30px;">CGI Environment</h2>
  <table>
    <tr><th>Variable</th><th>Value</th></tr>""".format(name=name))

for key, value in sorted(os.environ.items()):
    print("    <tr><td>{}</td><td>{}</td></tr>".format(key, value))

if body:
    print("  </table>")
    print("  <h2 style='color:#888;margin-top:20px;'>POST Body</h2>")
    print("  <pre style='background:#1a1a2e;padding:12px;border-radius:4px;'>{}</pre>".format(body))
else:
    print("  </table>")

print("""  <p style="margin-top:20px;"><a class="back" href="/">← Back</a></p>
</body>
</html>""")
